import Head from "next/head";
import { Image } from "@chakra-ui/react";
import {
  Flex,
  Container,
  Heading,
  Stack,
  Text,
  Box,
  SimpleGrid
} from "@chakra-ui/react";
import { useQuery } from "urql";

const MorieQuery = `
  query {
		tokens(first: 50) {
			id
			tokenID
			imageURI
		}
	}
`;

export default function Home() {
  const [result, reexecuteQuery] = useQuery({
    query: MorieQuery,
  });

  const { data, fetching, error } = result;

  if (!data) {
    return null;
  }

  return (
    <div>
      <Head>
        <title>Mories Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW={"5xl"}>
          <Stack
            textAlign={"center"}
            align={"center"}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 20, md: 28 }}
          >
            <Heading
              fontWeight={600}
              fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
              lineHeight={"110%"}
            >
              test
            </Heading>
            <Text color={"gray.500"} maxW={"3xl"}>
              &quot;memento mori&quot; is a latin saying that means
              &quot;Remember you die&quot;.
            </Text>
            <SimpleGrid columns={{base: 2, lg: 4}} spacing={0}>
              {data?.tokens &&
                data.tokens.map((token) => {
                  return (
                    <Box boxSize="xs" key={token.tokenID}>
                      <Image src={token.imageURI} alt="" />
                    </Box>
                  );
                })}
            </SimpleGrid>
          </Stack>
        </Container>
      </main>
    </div>
  );
}
