import Head from "next/head";
import {
  Flex,
  Container,
  Heading,
  Stack,
  Text,
  Button,
  Icon,
  IconProps,
  Box,
} from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mories Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW={"5xl"}>
          <Stack
            textAlign={"center"}
            align={"center"}
            spacing={{ base: 8, md: 10 }}
            py={{ base: 20, md: 28 }}
          >
            <Heading
              fontWeight={600}
              fontSize={{ base: "3xl", sm: "4xl", md: "6xl" }}
              lineHeight={"110%"}
            >
              cryptomories
            </Heading>
            <Text color={"gray.500"} maxW={"3xl"}>
              &quot;memento mori&quot; is a latin saying that means
              &quot;Remember you die&quot;.
            </Text>
            <Stack spacing={6} direction={"row"}>
              <Button
                rounded={"full"}
                px={6}
                colorScheme={"orange"}
                bg={"orange.400"}
                _hover={{ bg: "orange.500" }}
              >
                Get started
              </Button>
              <Button rounded={"full"} px={6}>
                Learn more
              </Button>
            </Stack>
            <Flex w={"full"}>
              <Box>
                <Text>Image could go here</Text>
              </Box>
            </Flex>
          </Stack>
        </Container>
      </main>
    </div>
  );
}
