import Head from "next/head";
import Image from "next/image";
import { Box, Container, Stack, Text, Wrap, WrapItem } from "@chakra-ui/react";
import { useQuery } from "urql";

const MorieQuery = `
  query {
		tokens(first: 100) {
			id
			tokenID
			imageURI
		}
	}
`;

export default function Home() {
  const [result, reexecuteQuery] = useQuery({
    query: MorieQuery,
  });

  const { data, fetching, error } = result;

  if (!data) {
    return null;
  }

  return (
    <div>
      <Head>
        <title>Mories Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxW={"5xl"}>
          <Stack
            textAlign={"center"}
            align={"center"}
            spacing={{ base: 2, md: 6 }}
            py={{ base: 20, md: 28 }}
          >
            <Text
              bgGradient="linear(to-l, #7928CA, #FF0080)"
              bgClip="text"
              fontSize="6xl"
              fontWeight="extrabold"
              as="h1"
            >
              CryptoMories
            </Text>
            <Text color={"gray.900"}>
              &quot;memento mori&quot; is a latin saying that means
              &quot;Remember you die&quot;.
            </Text>
            <Wrap>
              {data?.tokens &&
                data.tokens.map((token) => {
                  return (
                    <WrapItem key={token.tokenID}>
                      <Image
                        height={100}
                        width={100}
                        src={token.imageURI}
                        alt=""
                      />
                    </WrapItem>
                  );
                })}
            </Wrap>
          </Stack>
        </Container>
      </main>
    </div>
  );
}
